apiVersion: v1
kind: Pod
metadata:
  name: writer-reader-pod
spec:
  containers:
  - name: writer
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          echo "$(date) writing log entry" >> /shared/log.txt;
          sleep 2;
        done;
    volumeMounts:
    - name: shared-logs
      mountPath: /shared

  - name: reader
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["tail -f /shared/log.txt"]
    volumeMounts:
    - name: shared-logs
      mountPath: /shared

  volumes:
  - name: shared-logs
    emptyDir: {}
